testonly: False
with-expecter: True
keeptree: True

packages:
  s-belichenko/house-tg-bot/pkg/time:
    config:
      filename: "{{.InterfaceName | snakecase}}.go"
      dir: "{{.InterfaceDir}}/mocks"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
      inpackage: true
  s-belichenko/house-tg-bot/pkg/logger:
    config:
      filename: "{{.InterfaceName | snakecase}}.go"
      dir: "{{.InterfaceDir}}/mocks"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
      inpackage: true