// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	telebot "gopkg.in/telebot.v4"

	time "time"
)

// TeleContext is an autogenerated mock type for the TeleContext type
type TeleContext struct {
	mock.Mock
}

type TeleContext_Expecter struct {
	mock *mock.Mock
}

func (_m *TeleContext) EXPECT() *TeleContext_Expecter {
	return &TeleContext_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function with given fields: errorMessage
func (_m *TeleContext) Accept(errorMessage ...string) error {
	_va := make([]interface{}, len(errorMessage))
	for _i := range errorMessage {
		_va[_i] = errorMessage[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...string) error); ok {
		r0 = rf(errorMessage...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type TeleContext_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - errorMessage ...string
func (_e *TeleContext_Expecter) Accept(errorMessage ...interface{}) *TeleContext_Accept_Call {
	return &TeleContext_Accept_Call{Call: _e.mock.On("Accept",
		append([]interface{}{}, errorMessage...)...)}
}

func (_c *TeleContext_Accept_Call) Run(run func(errorMessage ...string)) *TeleContext_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_Accept_Call) Return(_a0 error) *TeleContext_Accept_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Accept_Call) RunAndReturn(run func(...string) error) *TeleContext_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Answer provides a mock function with given fields: resp
func (_m *TeleContext) Answer(resp *telebot.QueryResponse) error {
	ret := _m.Called(resp)

	if len(ret) == 0 {
		panic("no return value specified for Answer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*telebot.QueryResponse) error); ok {
		r0 = rf(resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Answer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Answer'
type TeleContext_Answer_Call struct {
	*mock.Call
}

// Answer is a helper method to define mock.On call
//   - resp *telebot.QueryResponse
func (_e *TeleContext_Expecter) Answer(resp interface{}) *TeleContext_Answer_Call {
	return &TeleContext_Answer_Call{Call: _e.mock.On("Answer", resp)}
}

func (_c *TeleContext_Answer_Call) Run(run func(resp *telebot.QueryResponse)) *TeleContext_Answer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*telebot.QueryResponse))
	})
	return _c
}

func (_c *TeleContext_Answer_Call) Return(_a0 error) *TeleContext_Answer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Answer_Call) RunAndReturn(run func(*telebot.QueryResponse) error) *TeleContext_Answer_Call {
	_c.Call.Return(run)
	return _c
}

// Args provides a mock function with no fields
func (_m *TeleContext) Args() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Args")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// TeleContext_Args_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Args'
type TeleContext_Args_Call struct {
	*mock.Call
}

// Args is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Args() *TeleContext_Args_Call {
	return &TeleContext_Args_Call{Call: _e.mock.On("Args")}
}

func (_c *TeleContext_Args_Call) Run(run func()) *TeleContext_Args_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Args_Call) Return(_a0 []string) *TeleContext_Args_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Args_Call) RunAndReturn(run func() []string) *TeleContext_Args_Call {
	_c.Call.Return(run)
	return _c
}

// Boost provides a mock function with no fields
func (_m *TeleContext) Boost() *telebot.BoostUpdated {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Boost")
	}

	var r0 *telebot.BoostUpdated
	if rf, ok := ret.Get(0).(func() *telebot.BoostUpdated); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.BoostUpdated)
		}
	}

	return r0
}

// TeleContext_Boost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Boost'
type TeleContext_Boost_Call struct {
	*mock.Call
}

// Boost is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Boost() *TeleContext_Boost_Call {
	return &TeleContext_Boost_Call{Call: _e.mock.On("Boost")}
}

func (_c *TeleContext_Boost_Call) Run(run func()) *TeleContext_Boost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Boost_Call) Return(_a0 *telebot.BoostUpdated) *TeleContext_Boost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Boost_Call) RunAndReturn(run func() *telebot.BoostUpdated) *TeleContext_Boost_Call {
	_c.Call.Return(run)
	return _c
}

// BoostRemoved provides a mock function with no fields
func (_m *TeleContext) BoostRemoved() *telebot.BoostRemoved {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BoostRemoved")
	}

	var r0 *telebot.BoostRemoved
	if rf, ok := ret.Get(0).(func() *telebot.BoostRemoved); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.BoostRemoved)
		}
	}

	return r0
}

// TeleContext_BoostRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BoostRemoved'
type TeleContext_BoostRemoved_Call struct {
	*mock.Call
}

// BoostRemoved is a helper method to define mock.On call
func (_e *TeleContext_Expecter) BoostRemoved() *TeleContext_BoostRemoved_Call {
	return &TeleContext_BoostRemoved_Call{Call: _e.mock.On("BoostRemoved")}
}

func (_c *TeleContext_BoostRemoved_Call) Run(run func()) *TeleContext_BoostRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_BoostRemoved_Call) Return(_a0 *telebot.BoostRemoved) *TeleContext_BoostRemoved_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_BoostRemoved_Call) RunAndReturn(run func() *telebot.BoostRemoved) *TeleContext_BoostRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// Bot provides a mock function with no fields
func (_m *TeleContext) Bot() telebot.API {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bot")
	}

	var r0 telebot.API
	if rf, ok := ret.Get(0).(func() telebot.API); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telebot.API)
		}
	}

	return r0
}

// TeleContext_Bot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bot'
type TeleContext_Bot_Call struct {
	*mock.Call
}

// Bot is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Bot() *TeleContext_Bot_Call {
	return &TeleContext_Bot_Call{Call: _e.mock.On("Bot")}
}

func (_c *TeleContext_Bot_Call) Run(run func()) *TeleContext_Bot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Bot_Call) Return(_a0 telebot.API) *TeleContext_Bot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Bot_Call) RunAndReturn(run func() telebot.API) *TeleContext_Bot_Call {
	_c.Call.Return(run)
	return _c
}

// Callback provides a mock function with no fields
func (_m *TeleContext) Callback() *telebot.Callback {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Callback")
	}

	var r0 *telebot.Callback
	if rf, ok := ret.Get(0).(func() *telebot.Callback); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Callback)
		}
	}

	return r0
}

// TeleContext_Callback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Callback'
type TeleContext_Callback_Call struct {
	*mock.Call
}

// Callback is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Callback() *TeleContext_Callback_Call {
	return &TeleContext_Callback_Call{Call: _e.mock.On("Callback")}
}

func (_c *TeleContext_Callback_Call) Run(run func()) *TeleContext_Callback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Callback_Call) Return(_a0 *telebot.Callback) *TeleContext_Callback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Callback_Call) RunAndReturn(run func() *telebot.Callback) *TeleContext_Callback_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function with no fields
func (_m *TeleContext) Chat() *telebot.Chat {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *telebot.Chat
	if rf, ok := ret.Get(0).(func() *telebot.Chat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Chat)
		}
	}

	return r0
}

// TeleContext_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type TeleContext_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Chat() *TeleContext_Chat_Call {
	return &TeleContext_Chat_Call{Call: _e.mock.On("Chat")}
}

func (_c *TeleContext_Chat_Call) Run(run func()) *TeleContext_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Chat_Call) Return(_a0 *telebot.Chat) *TeleContext_Chat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Chat_Call) RunAndReturn(run func() *telebot.Chat) *TeleContext_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// ChatJoinRequest provides a mock function with no fields
func (_m *TeleContext) ChatJoinRequest() *telebot.ChatJoinRequest {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatJoinRequest")
	}

	var r0 *telebot.ChatJoinRequest
	if rf, ok := ret.Get(0).(func() *telebot.ChatJoinRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ChatJoinRequest)
		}
	}

	return r0
}

// TeleContext_ChatJoinRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatJoinRequest'
type TeleContext_ChatJoinRequest_Call struct {
	*mock.Call
}

// ChatJoinRequest is a helper method to define mock.On call
func (_e *TeleContext_Expecter) ChatJoinRequest() *TeleContext_ChatJoinRequest_Call {
	return &TeleContext_ChatJoinRequest_Call{Call: _e.mock.On("ChatJoinRequest")}
}

func (_c *TeleContext_ChatJoinRequest_Call) Run(run func()) *TeleContext_ChatJoinRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_ChatJoinRequest_Call) Return(_a0 *telebot.ChatJoinRequest) *TeleContext_ChatJoinRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_ChatJoinRequest_Call) RunAndReturn(run func() *telebot.ChatJoinRequest) *TeleContext_ChatJoinRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ChatMember provides a mock function with no fields
func (_m *TeleContext) ChatMember() *telebot.ChatMemberUpdate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatMember")
	}

	var r0 *telebot.ChatMemberUpdate
	if rf, ok := ret.Get(0).(func() *telebot.ChatMemberUpdate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ChatMemberUpdate)
		}
	}

	return r0
}

// TeleContext_ChatMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatMember'
type TeleContext_ChatMember_Call struct {
	*mock.Call
}

// ChatMember is a helper method to define mock.On call
func (_e *TeleContext_Expecter) ChatMember() *TeleContext_ChatMember_Call {
	return &TeleContext_ChatMember_Call{Call: _e.mock.On("ChatMember")}
}

func (_c *TeleContext_ChatMember_Call) Run(run func()) *TeleContext_ChatMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_ChatMember_Call) Return(_a0 *telebot.ChatMemberUpdate) *TeleContext_ChatMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_ChatMember_Call) RunAndReturn(run func() *telebot.ChatMemberUpdate) *TeleContext_ChatMember_Call {
	_c.Call.Return(run)
	return _c
}

// Data provides a mock function with no fields
func (_m *TeleContext) Data() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TeleContext_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type TeleContext_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Data() *TeleContext_Data_Call {
	return &TeleContext_Data_Call{Call: _e.mock.On("Data")}
}

func (_c *TeleContext_Data_Call) Run(run func()) *TeleContext_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Data_Call) Return(_a0 string) *TeleContext_Data_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Data_Call) RunAndReturn(run func() string) *TeleContext_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with no fields
func (_m *TeleContext) Delete() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TeleContext_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Delete() *TeleContext_Delete_Call {
	return &TeleContext_Delete_Call{Call: _e.mock.On("Delete")}
}

func (_c *TeleContext_Delete_Call) Run(run func()) *TeleContext_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Delete_Call) Return(_a0 error) *TeleContext_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Delete_Call) RunAndReturn(run func() error) *TeleContext_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAfter provides a mock function with given fields: d
func (_m *TeleContext) DeleteAfter(d time.Duration) *time.Timer {
	ret := _m.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAfter")
	}

	var r0 *time.Timer
	if rf, ok := ret.Get(0).(func(time.Duration) *time.Timer); ok {
		r0 = rf(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Timer)
		}
	}

	return r0
}

// TeleContext_DeleteAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAfter'
type TeleContext_DeleteAfter_Call struct {
	*mock.Call
}

// DeleteAfter is a helper method to define mock.On call
//   - d time.Duration
func (_e *TeleContext_Expecter) DeleteAfter(d interface{}) *TeleContext_DeleteAfter_Call {
	return &TeleContext_DeleteAfter_Call{Call: _e.mock.On("DeleteAfter", d)}
}

func (_c *TeleContext_DeleteAfter_Call) Run(run func(d time.Duration)) *TeleContext_DeleteAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *TeleContext_DeleteAfter_Call) Return(_a0 *time.Timer) *TeleContext_DeleteAfter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_DeleteAfter_Call) RunAndReturn(run func(time.Duration) *time.Timer) *TeleContext_DeleteAfter_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function with given fields: what, opts
func (_m *TeleContext) Edit(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type TeleContext_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *TeleContext_Expecter) Edit(what interface{}, opts ...interface{}) *TeleContext_Edit_Call {
	return &TeleContext_Edit_Call{Call: _e.mock.On("Edit",
		append([]interface{}{what}, opts...)...)}
}

func (_c *TeleContext_Edit_Call) Run(run func(what interface{}, opts ...interface{})) *TeleContext_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_Edit_Call) Return(_a0 error) *TeleContext_Edit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Edit_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *TeleContext_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// EditCaption provides a mock function with given fields: caption, opts
func (_m *TeleContext) EditCaption(caption string, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, caption)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EditCaption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) error); ok {
		r0 = rf(caption, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_EditCaption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditCaption'
type TeleContext_EditCaption_Call struct {
	*mock.Call
}

// EditCaption is a helper method to define mock.On call
//   - caption string
//   - opts ...interface{}
func (_e *TeleContext_Expecter) EditCaption(caption interface{}, opts ...interface{}) *TeleContext_EditCaption_Call {
	return &TeleContext_EditCaption_Call{Call: _e.mock.On("EditCaption",
		append([]interface{}{caption}, opts...)...)}
}

func (_c *TeleContext_EditCaption_Call) Run(run func(caption string, opts ...interface{})) *TeleContext_EditCaption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_EditCaption_Call) Return(_a0 error) *TeleContext_EditCaption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_EditCaption_Call) RunAndReturn(run func(string, ...interface{}) error) *TeleContext_EditCaption_Call {
	_c.Call.Return(run)
	return _c
}

// EditOrReply provides a mock function with given fields: what, opts
func (_m *TeleContext) EditOrReply(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EditOrReply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_EditOrReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditOrReply'
type TeleContext_EditOrReply_Call struct {
	*mock.Call
}

// EditOrReply is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *TeleContext_Expecter) EditOrReply(what interface{}, opts ...interface{}) *TeleContext_EditOrReply_Call {
	return &TeleContext_EditOrReply_Call{Call: _e.mock.On("EditOrReply",
		append([]interface{}{what}, opts...)...)}
}

func (_c *TeleContext_EditOrReply_Call) Run(run func(what interface{}, opts ...interface{})) *TeleContext_EditOrReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_EditOrReply_Call) Return(_a0 error) *TeleContext_EditOrReply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_EditOrReply_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *TeleContext_EditOrReply_Call {
	_c.Call.Return(run)
	return _c
}

// EditOrSend provides a mock function with given fields: what, opts
func (_m *TeleContext) EditOrSend(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EditOrSend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_EditOrSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditOrSend'
type TeleContext_EditOrSend_Call struct {
	*mock.Call
}

// EditOrSend is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *TeleContext_Expecter) EditOrSend(what interface{}, opts ...interface{}) *TeleContext_EditOrSend_Call {
	return &TeleContext_EditOrSend_Call{Call: _e.mock.On("EditOrSend",
		append([]interface{}{what}, opts...)...)}
}

func (_c *TeleContext_EditOrSend_Call) Run(run func(what interface{}, opts ...interface{})) *TeleContext_EditOrSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_EditOrSend_Call) Return(_a0 error) *TeleContext_EditOrSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_EditOrSend_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *TeleContext_EditOrSend_Call {
	_c.Call.Return(run)
	return _c
}

// Entities provides a mock function with no fields
func (_m *TeleContext) Entities() telebot.Entities {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Entities")
	}

	var r0 telebot.Entities
	if rf, ok := ret.Get(0).(func() telebot.Entities); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telebot.Entities)
		}
	}

	return r0
}

// TeleContext_Entities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entities'
type TeleContext_Entities_Call struct {
	*mock.Call
}

// Entities is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Entities() *TeleContext_Entities_Call {
	return &TeleContext_Entities_Call{Call: _e.mock.On("Entities")}
}

func (_c *TeleContext_Entities_Call) Run(run func()) *TeleContext_Entities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Entities_Call) Return(_a0 telebot.Entities) *TeleContext_Entities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Entities_Call) RunAndReturn(run func() telebot.Entities) *TeleContext_Entities_Call {
	_c.Call.Return(run)
	return _c
}

// Forward provides a mock function with given fields: msg, opts
func (_m *TeleContext) Forward(msg telebot.Editable, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Forward")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(telebot.Editable, ...interface{}) error); ok {
		r0 = rf(msg, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type TeleContext_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - msg telebot.Editable
//   - opts ...interface{}
func (_e *TeleContext_Expecter) Forward(msg interface{}, opts ...interface{}) *TeleContext_Forward_Call {
	return &TeleContext_Forward_Call{Call: _e.mock.On("Forward",
		append([]interface{}{msg}, opts...)...)}
}

func (_c *TeleContext_Forward_Call) Run(run func(msg telebot.Editable, opts ...interface{})) *TeleContext_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(telebot.Editable), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_Forward_Call) Return(_a0 error) *TeleContext_Forward_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Forward_Call) RunAndReturn(run func(telebot.Editable, ...interface{}) error) *TeleContext_Forward_Call {
	_c.Call.Return(run)
	return _c
}

// ForwardTo provides a mock function with given fields: to, opts
func (_m *TeleContext) ForwardTo(to telebot.Recipient, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, to)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ForwardTo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(telebot.Recipient, ...interface{}) error); ok {
		r0 = rf(to, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_ForwardTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardTo'
type TeleContext_ForwardTo_Call struct {
	*mock.Call
}

// ForwardTo is a helper method to define mock.On call
//   - to telebot.Recipient
//   - opts ...interface{}
func (_e *TeleContext_Expecter) ForwardTo(to interface{}, opts ...interface{}) *TeleContext_ForwardTo_Call {
	return &TeleContext_ForwardTo_Call{Call: _e.mock.On("ForwardTo",
		append([]interface{}{to}, opts...)...)}
}

func (_c *TeleContext_ForwardTo_Call) Run(run func(to telebot.Recipient, opts ...interface{})) *TeleContext_ForwardTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(telebot.Recipient), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_ForwardTo_Call) Return(_a0 error) *TeleContext_ForwardTo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_ForwardTo_Call) RunAndReturn(run func(telebot.Recipient, ...interface{}) error) *TeleContext_ForwardTo_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *TeleContext) Get(key string) interface{} {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// TeleContext_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TeleContext_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *TeleContext_Expecter) Get(key interface{}) *TeleContext_Get_Call {
	return &TeleContext_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *TeleContext_Get_Call) Run(run func(key string)) *TeleContext_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TeleContext_Get_Call) Return(_a0 interface{}) *TeleContext_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Get_Call) RunAndReturn(run func(string) interface{}) *TeleContext_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InlineResult provides a mock function with no fields
func (_m *TeleContext) InlineResult() *telebot.InlineResult {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InlineResult")
	}

	var r0 *telebot.InlineResult
	if rf, ok := ret.Get(0).(func() *telebot.InlineResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.InlineResult)
		}
	}

	return r0
}

// TeleContext_InlineResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InlineResult'
type TeleContext_InlineResult_Call struct {
	*mock.Call
}

// InlineResult is a helper method to define mock.On call
func (_e *TeleContext_Expecter) InlineResult() *TeleContext_InlineResult_Call {
	return &TeleContext_InlineResult_Call{Call: _e.mock.On("InlineResult")}
}

func (_c *TeleContext_InlineResult_Call) Run(run func()) *TeleContext_InlineResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_InlineResult_Call) Return(_a0 *telebot.InlineResult) *TeleContext_InlineResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_InlineResult_Call) RunAndReturn(run func() *telebot.InlineResult) *TeleContext_InlineResult_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function with no fields
func (_m *TeleContext) Message() *telebot.Message {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 *telebot.Message
	if rf, ok := ret.Get(0).(func() *telebot.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Message)
		}
	}

	return r0
}

// TeleContext_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type TeleContext_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Message() *TeleContext_Message_Call {
	return &TeleContext_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *TeleContext_Message_Call) Run(run func()) *TeleContext_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Message_Call) Return(_a0 *telebot.Message) *TeleContext_Message_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Message_Call) RunAndReturn(run func() *telebot.Message) *TeleContext_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Migration provides a mock function with no fields
func (_m *TeleContext) Migration() (int64, int64) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Migration")
	}

	var r0 int64
	var r1 int64
	if rf, ok := ret.Get(0).(func() (int64, int64)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() int64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int64)
	}

	return r0, r1
}

// TeleContext_Migration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migration'
type TeleContext_Migration_Call struct {
	*mock.Call
}

// Migration is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Migration() *TeleContext_Migration_Call {
	return &TeleContext_Migration_Call{Call: _e.mock.On("Migration")}
}

func (_c *TeleContext_Migration_Call) Run(run func()) *TeleContext_Migration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Migration_Call) Return(_a0 int64, _a1 int64) *TeleContext_Migration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeleContext_Migration_Call) RunAndReturn(run func() (int64, int64)) *TeleContext_Migration_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function with given fields: action
func (_m *TeleContext) Notify(action telebot.ChatAction) error {
	ret := _m.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(telebot.ChatAction) error); ok {
		r0 = rf(action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type TeleContext_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - action telebot.ChatAction
func (_e *TeleContext_Expecter) Notify(action interface{}) *TeleContext_Notify_Call {
	return &TeleContext_Notify_Call{Call: _e.mock.On("Notify", action)}
}

func (_c *TeleContext_Notify_Call) Run(run func(action telebot.ChatAction)) *TeleContext_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(telebot.ChatAction))
	})
	return _c
}

func (_c *TeleContext_Notify_Call) Return(_a0 error) *TeleContext_Notify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Notify_Call) RunAndReturn(run func(telebot.ChatAction) error) *TeleContext_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Payment provides a mock function with no fields
func (_m *TeleContext) Payment() *telebot.Payment {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payment")
	}

	var r0 *telebot.Payment
	if rf, ok := ret.Get(0).(func() *telebot.Payment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Payment)
		}
	}

	return r0
}

// TeleContext_Payment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payment'
type TeleContext_Payment_Call struct {
	*mock.Call
}

// Payment is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Payment() *TeleContext_Payment_Call {
	return &TeleContext_Payment_Call{Call: _e.mock.On("Payment")}
}

func (_c *TeleContext_Payment_Call) Run(run func()) *TeleContext_Payment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Payment_Call) Return(_a0 *telebot.Payment) *TeleContext_Payment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Payment_Call) RunAndReturn(run func() *telebot.Payment) *TeleContext_Payment_Call {
	_c.Call.Return(run)
	return _c
}

// Poll provides a mock function with no fields
func (_m *TeleContext) Poll() *telebot.Poll {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 *telebot.Poll
	if rf, ok := ret.Get(0).(func() *telebot.Poll); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Poll)
		}
	}

	return r0
}

// TeleContext_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type TeleContext_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Poll() *TeleContext_Poll_Call {
	return &TeleContext_Poll_Call{Call: _e.mock.On("Poll")}
}

func (_c *TeleContext_Poll_Call) Run(run func()) *TeleContext_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Poll_Call) Return(_a0 *telebot.Poll) *TeleContext_Poll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Poll_Call) RunAndReturn(run func() *telebot.Poll) *TeleContext_Poll_Call {
	_c.Call.Return(run)
	return _c
}

// PollAnswer provides a mock function with no fields
func (_m *TeleContext) PollAnswer() *telebot.PollAnswer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PollAnswer")
	}

	var r0 *telebot.PollAnswer
	if rf, ok := ret.Get(0).(func() *telebot.PollAnswer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.PollAnswer)
		}
	}

	return r0
}

// TeleContext_PollAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollAnswer'
type TeleContext_PollAnswer_Call struct {
	*mock.Call
}

// PollAnswer is a helper method to define mock.On call
func (_e *TeleContext_Expecter) PollAnswer() *TeleContext_PollAnswer_Call {
	return &TeleContext_PollAnswer_Call{Call: _e.mock.On("PollAnswer")}
}

func (_c *TeleContext_PollAnswer_Call) Run(run func()) *TeleContext_PollAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_PollAnswer_Call) Return(_a0 *telebot.PollAnswer) *TeleContext_PollAnswer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_PollAnswer_Call) RunAndReturn(run func() *telebot.PollAnswer) *TeleContext_PollAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// PreCheckoutQuery provides a mock function with no fields
func (_m *TeleContext) PreCheckoutQuery() *telebot.PreCheckoutQuery {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreCheckoutQuery")
	}

	var r0 *telebot.PreCheckoutQuery
	if rf, ok := ret.Get(0).(func() *telebot.PreCheckoutQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.PreCheckoutQuery)
		}
	}

	return r0
}

// TeleContext_PreCheckoutQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreCheckoutQuery'
type TeleContext_PreCheckoutQuery_Call struct {
	*mock.Call
}

// PreCheckoutQuery is a helper method to define mock.On call
func (_e *TeleContext_Expecter) PreCheckoutQuery() *TeleContext_PreCheckoutQuery_Call {
	return &TeleContext_PreCheckoutQuery_Call{Call: _e.mock.On("PreCheckoutQuery")}
}

func (_c *TeleContext_PreCheckoutQuery_Call) Run(run func()) *TeleContext_PreCheckoutQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_PreCheckoutQuery_Call) Return(_a0 *telebot.PreCheckoutQuery) *TeleContext_PreCheckoutQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_PreCheckoutQuery_Call) RunAndReturn(run func() *telebot.PreCheckoutQuery) *TeleContext_PreCheckoutQuery_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with no fields
func (_m *TeleContext) Query() *telebot.Query {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *telebot.Query
	if rf, ok := ret.Get(0).(func() *telebot.Query); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Query)
		}
	}

	return r0
}

// TeleContext_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type TeleContext_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Query() *TeleContext_Query_Call {
	return &TeleContext_Query_Call{Call: _e.mock.On("Query")}
}

func (_c *TeleContext_Query_Call) Run(run func()) *TeleContext_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Query_Call) Return(_a0 *telebot.Query) *TeleContext_Query_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Query_Call) RunAndReturn(run func() *telebot.Query) *TeleContext_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Recipient provides a mock function with no fields
func (_m *TeleContext) Recipient() telebot.Recipient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recipient")
	}

	var r0 telebot.Recipient
	if rf, ok := ret.Get(0).(func() telebot.Recipient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telebot.Recipient)
		}
	}

	return r0
}

// TeleContext_Recipient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recipient'
type TeleContext_Recipient_Call struct {
	*mock.Call
}

// Recipient is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Recipient() *TeleContext_Recipient_Call {
	return &TeleContext_Recipient_Call{Call: _e.mock.On("Recipient")}
}

func (_c *TeleContext_Recipient_Call) Run(run func()) *TeleContext_Recipient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Recipient_Call) Return(_a0 telebot.Recipient) *TeleContext_Recipient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Recipient_Call) RunAndReturn(run func() telebot.Recipient) *TeleContext_Recipient_Call {
	_c.Call.Return(run)
	return _c
}

// Reply provides a mock function with given fields: what, opts
func (_m *TeleContext) Reply(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Reply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Reply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reply'
type TeleContext_Reply_Call struct {
	*mock.Call
}

// Reply is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *TeleContext_Expecter) Reply(what interface{}, opts ...interface{}) *TeleContext_Reply_Call {
	return &TeleContext_Reply_Call{Call: _e.mock.On("Reply",
		append([]interface{}{what}, opts...)...)}
}

func (_c *TeleContext_Reply_Call) Run(run func(what interface{}, opts ...interface{})) *TeleContext_Reply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_Reply_Call) Return(_a0 error) *TeleContext_Reply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Reply_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *TeleContext_Reply_Call {
	_c.Call.Return(run)
	return _c
}

// Respond provides a mock function with given fields: resp
func (_m *TeleContext) Respond(resp ...*telebot.CallbackResponse) error {
	_va := make([]interface{}, len(resp))
	for _i := range resp {
		_va[_i] = resp[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Respond")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...*telebot.CallbackResponse) error); ok {
		r0 = rf(resp...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Respond_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Respond'
type TeleContext_Respond_Call struct {
	*mock.Call
}

// Respond is a helper method to define mock.On call
//   - resp ...*telebot.CallbackResponse
func (_e *TeleContext_Expecter) Respond(resp ...interface{}) *TeleContext_Respond_Call {
	return &TeleContext_Respond_Call{Call: _e.mock.On("Respond",
		append([]interface{}{}, resp...)...)}
}

func (_c *TeleContext_Respond_Call) Run(run func(resp ...*telebot.CallbackResponse)) *TeleContext_Respond_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*telebot.CallbackResponse, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(*telebot.CallbackResponse)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_Respond_Call) Return(_a0 error) *TeleContext_Respond_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Respond_Call) RunAndReturn(run func(...*telebot.CallbackResponse) error) *TeleContext_Respond_Call {
	_c.Call.Return(run)
	return _c
}

// RespondAlert provides a mock function with given fields: text
func (_m *TeleContext) RespondAlert(text string) error {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for RespondAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_RespondAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RespondAlert'
type TeleContext_RespondAlert_Call struct {
	*mock.Call
}

// RespondAlert is a helper method to define mock.On call
//   - text string
func (_e *TeleContext_Expecter) RespondAlert(text interface{}) *TeleContext_RespondAlert_Call {
	return &TeleContext_RespondAlert_Call{Call: _e.mock.On("RespondAlert", text)}
}

func (_c *TeleContext_RespondAlert_Call) Run(run func(text string)) *TeleContext_RespondAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TeleContext_RespondAlert_Call) Return(_a0 error) *TeleContext_RespondAlert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_RespondAlert_Call) RunAndReturn(run func(string) error) *TeleContext_RespondAlert_Call {
	_c.Call.Return(run)
	return _c
}

// RespondText provides a mock function with given fields: text
func (_m *TeleContext) RespondText(text string) error {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for RespondText")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_RespondText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RespondText'
type TeleContext_RespondText_Call struct {
	*mock.Call
}

// RespondText is a helper method to define mock.On call
//   - text string
func (_e *TeleContext_Expecter) RespondText(text interface{}) *TeleContext_RespondText_Call {
	return &TeleContext_RespondText_Call{Call: _e.mock.On("RespondText", text)}
}

func (_c *TeleContext_RespondText_Call) Run(run func(text string)) *TeleContext_RespondText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TeleContext_RespondText_Call) Return(_a0 error) *TeleContext_RespondText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_RespondText_Call) RunAndReturn(run func(string) error) *TeleContext_RespondText_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: what, opts
func (_m *TeleContext) Send(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type TeleContext_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *TeleContext_Expecter) Send(what interface{}, opts ...interface{}) *TeleContext_Send_Call {
	return &TeleContext_Send_Call{Call: _e.mock.On("Send",
		append([]interface{}{what}, opts...)...)}
}

func (_c *TeleContext_Send_Call) Run(run func(what interface{}, opts ...interface{})) *TeleContext_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_Send_Call) Return(_a0 error) *TeleContext_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Send_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *TeleContext_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendAlbum provides a mock function with given fields: a, opts
func (_m *TeleContext) SendAlbum(a telebot.Album, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, a)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(telebot.Album, ...interface{}) error); ok {
		r0 = rf(a, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_SendAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAlbum'
type TeleContext_SendAlbum_Call struct {
	*mock.Call
}

// SendAlbum is a helper method to define mock.On call
//   - a telebot.Album
//   - opts ...interface{}
func (_e *TeleContext_Expecter) SendAlbum(a interface{}, opts ...interface{}) *TeleContext_SendAlbum_Call {
	return &TeleContext_SendAlbum_Call{Call: _e.mock.On("SendAlbum",
		append([]interface{}{a}, opts...)...)}
}

func (_c *TeleContext_SendAlbum_Call) Run(run func(a telebot.Album, opts ...interface{})) *TeleContext_SendAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(telebot.Album), variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_SendAlbum_Call) Return(_a0 error) *TeleContext_SendAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_SendAlbum_Call) RunAndReturn(run func(telebot.Album, ...interface{}) error) *TeleContext_SendAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// Sender provides a mock function with no fields
func (_m *TeleContext) Sender() *telebot.User {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sender")
	}

	var r0 *telebot.User
	if rf, ok := ret.Get(0).(func() *telebot.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.User)
		}
	}

	return r0
}

// TeleContext_Sender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sender'
type TeleContext_Sender_Call struct {
	*mock.Call
}

// Sender is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Sender() *TeleContext_Sender_Call {
	return &TeleContext_Sender_Call{Call: _e.mock.On("Sender")}
}

func (_c *TeleContext_Sender_Call) Run(run func()) *TeleContext_Sender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Sender_Call) Return(_a0 *telebot.User) *TeleContext_Sender_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Sender_Call) RunAndReturn(run func() *telebot.User) *TeleContext_Sender_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, val
func (_m *TeleContext) Set(key string, val interface{}) {
	_m.Called(key, val)
}

// TeleContext_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type TeleContext_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - val interface{}
func (_e *TeleContext_Expecter) Set(key interface{}, val interface{}) *TeleContext_Set_Call {
	return &TeleContext_Set_Call{Call: _e.mock.On("Set", key, val)}
}

func (_c *TeleContext_Set_Call) Run(run func(key string, val interface{})) *TeleContext_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *TeleContext_Set_Call) Return() *TeleContext_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *TeleContext_Set_Call) RunAndReturn(run func(string, interface{})) *TeleContext_Set_Call {
	_c.Run(run)
	return _c
}

// Ship provides a mock function with given fields: what
func (_m *TeleContext) Ship(what ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ship")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(what...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeleContext_Ship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ship'
type TeleContext_Ship_Call struct {
	*mock.Call
}

// Ship is a helper method to define mock.On call
//   - what ...interface{}
func (_e *TeleContext_Expecter) Ship(what ...interface{}) *TeleContext_Ship_Call {
	return &TeleContext_Ship_Call{Call: _e.mock.On("Ship",
		append([]interface{}{}, what...)...)}
}

func (_c *TeleContext_Ship_Call) Run(run func(what ...interface{})) *TeleContext_Ship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *TeleContext_Ship_Call) Return(_a0 error) *TeleContext_Ship_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Ship_Call) RunAndReturn(run func(...interface{}) error) *TeleContext_Ship_Call {
	_c.Call.Return(run)
	return _c
}

// ShippingQuery provides a mock function with no fields
func (_m *TeleContext) ShippingQuery() *telebot.ShippingQuery {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShippingQuery")
	}

	var r0 *telebot.ShippingQuery
	if rf, ok := ret.Get(0).(func() *telebot.ShippingQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ShippingQuery)
		}
	}

	return r0
}

// TeleContext_ShippingQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShippingQuery'
type TeleContext_ShippingQuery_Call struct {
	*mock.Call
}

// ShippingQuery is a helper method to define mock.On call
func (_e *TeleContext_Expecter) ShippingQuery() *TeleContext_ShippingQuery_Call {
	return &TeleContext_ShippingQuery_Call{Call: _e.mock.On("ShippingQuery")}
}

func (_c *TeleContext_ShippingQuery_Call) Run(run func()) *TeleContext_ShippingQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_ShippingQuery_Call) Return(_a0 *telebot.ShippingQuery) *TeleContext_ShippingQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_ShippingQuery_Call) RunAndReturn(run func() *telebot.ShippingQuery) *TeleContext_ShippingQuery_Call {
	_c.Call.Return(run)
	return _c
}

// Text provides a mock function with no fields
func (_m *TeleContext) Text() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Text")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TeleContext_Text_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Text'
type TeleContext_Text_Call struct {
	*mock.Call
}

// Text is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Text() *TeleContext_Text_Call {
	return &TeleContext_Text_Call{Call: _e.mock.On("Text")}
}

func (_c *TeleContext_Text_Call) Run(run func()) *TeleContext_Text_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Text_Call) Return(_a0 string) *TeleContext_Text_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Text_Call) RunAndReturn(run func() string) *TeleContext_Text_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with no fields
func (_m *TeleContext) Topic() *telebot.Topic {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 *telebot.Topic
	if rf, ok := ret.Get(0).(func() *telebot.Topic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Topic)
		}
	}

	return r0
}

// TeleContext_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type TeleContext_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Topic() *TeleContext_Topic_Call {
	return &TeleContext_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *TeleContext_Topic_Call) Run(run func()) *TeleContext_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Topic_Call) Return(_a0 *telebot.Topic) *TeleContext_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Topic_Call) RunAndReturn(run func() *telebot.Topic) *TeleContext_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with no fields
func (_m *TeleContext) Update() telebot.Update {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 telebot.Update
	if rf, ok := ret.Get(0).(func() telebot.Update); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(telebot.Update)
	}

	return r0
}

// TeleContext_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TeleContext_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
func (_e *TeleContext_Expecter) Update() *TeleContext_Update_Call {
	return &TeleContext_Update_Call{Call: _e.mock.On("Update")}
}

func (_c *TeleContext_Update_Call) Run(run func()) *TeleContext_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TeleContext_Update_Call) Return(_a0 telebot.Update) *TeleContext_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeleContext_Update_Call) RunAndReturn(run func() telebot.Update) *TeleContext_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeleContext creates a new instance of TeleContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeleContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeleContext {
	mock := &TeleContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
