// Code generated by mockery v2.53.3. DO NOT EDIT.

package logger

import (
	pkglogger "s-belichenko/ilovaiskaya2-bot/pkg/logger"

	mock "github.com/stretchr/testify/mock"
)

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: message, context
func (_m *MockLogger) Debug(message string, context pkglogger.LogContext) {
	_m.Called(message, context)
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - message string
//   - context pkglogger.LogContext
func (_e *MockLogger_Expecter) Debug(message interface{}, context interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug", message, context)}
}

func (_c *MockLogger_Debug_Call) Run(run func(message string, context pkglogger.LogContext)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(pkglogger.LogContext))
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(string, pkglogger.LogContext)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: message, context
func (_m *MockLogger) Error(message string, context pkglogger.LogContext) {
	_m.Called(message, context)
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - message string
//   - context pkglogger.LogContext
func (_e *MockLogger_Expecter) Error(message interface{}, context interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error", message, context)}
}

func (_c *MockLogger_Error_Call) Run(run func(message string, context pkglogger.LogContext)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(pkglogger.LogContext))
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(string, pkglogger.LogContext)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function with given fields: message, context
func (_m *MockLogger) Fatal(message string, context pkglogger.LogContext) {
	_m.Called(message, context)
}

// MockLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - message string
//   - context pkglogger.LogContext
func (_e *MockLogger_Expecter) Fatal(message interface{}, context interface{}) *MockLogger_Fatal_Call {
	return &MockLogger_Fatal_Call{Call: _e.mock.On("Fatal", message, context)}
}

func (_c *MockLogger_Fatal_Call) Run(run func(message string, context pkglogger.LogContext)) *MockLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(pkglogger.LogContext))
	})
	return _c
}

func (_c *MockLogger_Fatal_Call) Return() *MockLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatal_Call) RunAndReturn(run func(string, pkglogger.LogContext)) *MockLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function with given fields: message, context
func (_m *MockLogger) Info(message string, context pkglogger.LogContext) {
	_m.Called(message, context)
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - message string
//   - context pkglogger.LogContext
func (_e *MockLogger_Expecter) Info(message interface{}, context interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info", message, context)}
}

func (_c *MockLogger_Info_Call) Run(run func(message string, context pkglogger.LogContext)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(pkglogger.LogContext))
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(string, pkglogger.LogContext)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Trace provides a mock function with given fields: message, context
func (_m *MockLogger) Trace(message string, context pkglogger.LogContext) {
	_m.Called(message, context)
}

// MockLogger_Trace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trace'
type MockLogger_Trace_Call struct {
	*mock.Call
}

// Trace is a helper method to define mock.On call
//   - message string
//   - context pkglogger.LogContext
func (_e *MockLogger_Expecter) Trace(message interface{}, context interface{}) *MockLogger_Trace_Call {
	return &MockLogger_Trace_Call{Call: _e.mock.On("Trace", message, context)}
}

func (_c *MockLogger_Trace_Call) Run(run func(message string, context pkglogger.LogContext)) *MockLogger_Trace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(pkglogger.LogContext))
	})
	return _c
}

func (_c *MockLogger_Trace_Call) Return() *MockLogger_Trace_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Trace_Call) RunAndReturn(run func(string, pkglogger.LogContext)) *MockLogger_Trace_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function with given fields: message, context
func (_m *MockLogger) Warn(message string, context pkglogger.LogContext) {
	_m.Called(message, context)
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - message string
//   - context pkglogger.LogContext
func (_e *MockLogger_Expecter) Warn(message interface{}, context interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn", message, context)}
}

func (_c *MockLogger_Warn_Call) Run(run func(message string, context pkglogger.LogContext)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(pkglogger.LogContext))
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(string, pkglogger.LogContext)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
