// Code generated by mockery v2.53.3. DO NOT EDIT.

package logger

import mock "github.com/stretchr/testify/mock"

// MockSystemLogger is an autogenerated mock type for the SystemLogger type
type MockSystemLogger struct {
	mock.Mock
}

type MockSystemLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemLogger) EXPECT() *MockSystemLogger_Expecter {
	return &MockSystemLogger_Expecter{mock: &_m.Mock}
}

// Fatal provides a mock function with given fields: args
func (_m *MockSystemLogger) Fatal(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSystemLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockSystemLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockSystemLogger_Expecter) Fatal(args ...interface{}) *MockSystemLogger_Fatal_Call {
	return &MockSystemLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{}, args...)...)}
}

func (_c *MockSystemLogger_Fatal_Call) Run(run func(args ...interface{})) *MockSystemLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockSystemLogger_Fatal_Call) Return() *MockSystemLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSystemLogger_Fatal_Call) RunAndReturn(run func(...interface{})) *MockSystemLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Fatalf provides a mock function with given fields: format, args
func (_m *MockSystemLogger) Fatalf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSystemLogger_Fatalf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalf'
type MockSystemLogger_Fatalf_Call struct {
	*mock.Call
}

// Fatalf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockSystemLogger_Expecter) Fatalf(format interface{}, args ...interface{}) *MockSystemLogger_Fatalf_Call {
	return &MockSystemLogger_Fatalf_Call{Call: _e.mock.On("Fatalf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockSystemLogger_Fatalf_Call) Run(run func(format string, args ...interface{})) *MockSystemLogger_Fatalf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSystemLogger_Fatalf_Call) Return() *MockSystemLogger_Fatalf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSystemLogger_Fatalf_Call) RunAndReturn(run func(string, ...interface{})) *MockSystemLogger_Fatalf_Call {
	_c.Run(run)
	return _c
}

// Fatalln provides a mock function with given fields: args
func (_m *MockSystemLogger) Fatalln(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSystemLogger_Fatalln_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalln'
type MockSystemLogger_Fatalln_Call struct {
	*mock.Call
}

// Fatalln is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockSystemLogger_Expecter) Fatalln(args ...interface{}) *MockSystemLogger_Fatalln_Call {
	return &MockSystemLogger_Fatalln_Call{Call: _e.mock.On("Fatalln",
		append([]interface{}{}, args...)...)}
}

func (_c *MockSystemLogger_Fatalln_Call) Run(run func(args ...interface{})) *MockSystemLogger_Fatalln_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockSystemLogger_Fatalln_Call) Return() *MockSystemLogger_Fatalln_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSystemLogger_Fatalln_Call) RunAndReturn(run func(...interface{})) *MockSystemLogger_Fatalln_Call {
	_c.Run(run)
	return _c
}

// Output provides a mock function with given fields: calldepth, s
func (_m *MockSystemLogger) Output(calldepth int, s string) error {
	ret := _m.Called(calldepth, s)

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(calldepth, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemLogger_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type MockSystemLogger_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
//   - calldepth int
//   - s string
func (_e *MockSystemLogger_Expecter) Output(calldepth interface{}, s interface{}) *MockSystemLogger_Output_Call {
	return &MockSystemLogger_Output_Call{Call: _e.mock.On("Output", calldepth, s)}
}

func (_c *MockSystemLogger_Output_Call) Run(run func(calldepth int, s string)) *MockSystemLogger_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string))
	})
	return _c
}

func (_c *MockSystemLogger_Output_Call) Return(_a0 error) *MockSystemLogger_Output_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemLogger_Output_Call) RunAndReturn(run func(int, string) error) *MockSystemLogger_Output_Call {
	_c.Call.Return(run)
	return _c
}

// Print provides a mock function with given fields: args
func (_m *MockSystemLogger) Print(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSystemLogger_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockSystemLogger_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockSystemLogger_Expecter) Print(args ...interface{}) *MockSystemLogger_Print_Call {
	return &MockSystemLogger_Print_Call{Call: _e.mock.On("Print",
		append([]interface{}{}, args...)...)}
}

func (_c *MockSystemLogger_Print_Call) Run(run func(args ...interface{})) *MockSystemLogger_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockSystemLogger_Print_Call) Return() *MockSystemLogger_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSystemLogger_Print_Call) RunAndReturn(run func(...interface{})) *MockSystemLogger_Print_Call {
	_c.Run(run)
	return _c
}

// Printf provides a mock function with given fields: format, args
func (_m *MockSystemLogger) Printf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSystemLogger_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type MockSystemLogger_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockSystemLogger_Expecter) Printf(format interface{}, args ...interface{}) *MockSystemLogger_Printf_Call {
	return &MockSystemLogger_Printf_Call{Call: _e.mock.On("Printf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockSystemLogger_Printf_Call) Run(run func(format string, args ...interface{})) *MockSystemLogger_Printf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSystemLogger_Printf_Call) Return() *MockSystemLogger_Printf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSystemLogger_Printf_Call) RunAndReturn(run func(string, ...interface{})) *MockSystemLogger_Printf_Call {
	_c.Run(run)
	return _c
}

// Println provides a mock function with given fields: args
func (_m *MockSystemLogger) Println(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockSystemLogger_Println_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Println'
type MockSystemLogger_Println_Call struct {
	*mock.Call
}

// Println is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockSystemLogger_Expecter) Println(args ...interface{}) *MockSystemLogger_Println_Call {
	return &MockSystemLogger_Println_Call{Call: _e.mock.On("Println",
		append([]interface{}{}, args...)...)}
}

func (_c *MockSystemLogger_Println_Call) Run(run func(args ...interface{})) *MockSystemLogger_Println_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockSystemLogger_Println_Call) Return() *MockSystemLogger_Println_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSystemLogger_Println_Call) RunAndReturn(run func(...interface{})) *MockSystemLogger_Println_Call {
	_c.Run(run)
	return _c
}

// NewMockSystemLogger creates a new instance of MockSystemLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemLogger {
	mock := &MockSystemLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
