on:
  push:
    branches:
      - main
      - development

jobs:
  Linters:
    runs-on: ubuntu-latest
    steps:
      # Загружаем код репозитория в окружение
      - name: Checkout repository
        uses: actions/checkout@v3
      # Устанавливаем Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5
          only-new-issues: false
          skip-cache: true
  Tests:
    needs:
      - Linters
    runs-on: ubuntu-latest
    steps:
      # Загружаем код репозитория в окружение
      - name: Checkout repository
        uses: actions/checkout@v3
      # Устанавливаем Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.0'
      # Запускаем модульные тесты
      - name: Run Go tests
        run: 'go test -cover -race ./...'
  Deploy:
    needs:
      - Tests
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    # Запускать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги
    steps:
      # Загружаем код репозитория в окружение
      - name: Checkout repository
        uses: actions/checkout@v3

      # Загружаем serverless-функцию в Yandex Cloud
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          function-name: ${{ secrets.YC_FUNCTION_NAME }}
          runtime: ${{ vars.FUNCTION_RUNTIME }}
          memory: ${{ vars.FUNCTION_MEMORY }}
          entrypoint: 'cmd/bot/main.Handler'
          service-account: ${{ secrets.YC_SERVICE_ACCOUT_ID }}
          # Переменные стоит передавать в кавычках, так как переменные тоже могут содержать их.ё
          environment: "
            HOUSE_CHAT_ID=${{ vars.HOUSE_CHAT_ID }}\n
            HOME_THREAD_BOT=${{ vars.HOME_THREAD_BOT }}\n
            ADMINISTRATION_CHAT_ID=${{ vars.ADMINISTRATION_CHAT_ID }}\n
            RULES_URL=${{ vars.RULES_URL }}\n
            OWNER_NICKNAME=${{ vars.OWNER_NICKNAME }}\n
            INVITE_URL=${{ vars.INVITE_URL }}\n
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}\n
            LLM_API_TOKEN=${{ secrets.LLM_API_TOKEN }}\n
            LLM_FOLDER_ID=${{ secrets.LLM_FOLDER_ID }}\n
            BOT_NAME=${{ vars.BOT_NAME }}\n
            BOT_NICKNAME=${{ vars.BOT_NICKNAME }}\n
            HOME_ADDRESS=${{ vars.HOME_ADDRESS }}\n
            VERIFY_RULES=${{ vars.VERIFY_RULES }}\n
            HOUSE_IS_COMPLETED=${{ vars.HOUSE_IS_COMPLETED }}\n"
          include: |
            ./cmd/**/*.go
            ./internal/**/*.go
            ./pkg/**/*.go
            ./pkg/template/templates/**/*.txt
            ./go.mod
          execution-timeout: ${{ vars.EXECUTION_TIMEOUT }}
          log-level: ${{ vars.LOG_LEVEL }}
          logs-group-id: ${{ secrets.LOG_GROUP_ID }}
